### ISSUE TITLE
Error if prompt contains new line or double quotes

### ISSUE THREAD

**Issue by sorro007** [jddev273/chatgpt-excel-function#1]
Gives following Error: 400 Bad Request.

**Comment by jddev273** [comment]
Hello,

Which function are you using?

If using the ChatGPT function you can pass a second parameter (prompt, TRUE), and the string will have be encoded.  

Example:

=ChatGPT("hello. 

how are you?

""I'm bob.""", TRUE)

**Comment by sorro007** [comment]
Thanks a lot. Using "TRUE" gave correct output.
